config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users, except: [:edit, :update , :index]

#   resources :boats do
#     resources :bookings
#   end
#   resources :bookings, except: [:new, :create] do
#     resources :reviews, only: [:new, :create, :show, :index]
#   end
# end


  resources :boats do
    resources :bookings, only: [:index, :show, :edit, :new, :create, :update, :destroy]
  end
  resources :bookings, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_name_and_location,
    against: [ :name, :location ],
    using: {
      tsearch: { prefix: true }
    }

  BOAT_CATEGORIES = %w[Bracera Banana-Boat Barge Dinghy Pedalo Punt Yacht Ship Catamaran Hovercraft]
  validates :name, :location, :price, :image_url, presence: true
  validates :boat_type, inclusion: { in: BOAT_CATEGORIES }
  validates :image_url, presence: true, allow_blank: true, format: { with: /(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-=\?]*)*\/?/ }
  validates :guests, inclusion: { in: 0..100 }, numericality: { only: true }
  validates :docked, inclusion: [true, false]

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
    { from: range[0], to: range[1] }
    end
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat
  has_many :reviews, dependent: :destroy

  validates :start_date, uniqueness: true, presence: true
  validates :end_date, uniqueness: true, presence: true

  validate :end_after_start
  validate :date_cannot_be_in_past


  private

  def end_after_start
    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def date_cannot_be_in_past
    if start_date < Date.today
      errors.add(:start_date, "cannot be in the past")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user

  validates :comment, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_boat, only: [:show, :destroy]

  def index
    @boats = policy_scope(Boat)
    if params[:query].present?
      @boats = Boat.search_by_name_and_location(params[:query])
    else
      @boats = policy_scope(Boat)
    end
  end

  def new
    @boat = Boat.new
    authorize @boat
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user_id = current_user
    authorize @boat
    if @boat.save
      redirect_to boat_path(@boat)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @bookings = @boat.bookings
  end

  def destroy
    @boat.destroy
    redirect_to boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :boat_id, :price, :location, :guests, :boat_type, :docked, :image_url)
  end

  def find_boat
    @boat = Boat.find (params[:id])
    authorize @boat
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy]
  before_action :find_boat, only: [:new, :create]

  def index
    bookings = policy_scope(Booking)
    @past_bookings = bookings.where("start_date <= '#{Date.today}'")
    @past_bookings.sort_by { |booking| booking.start_date }
    @future_bookings = bookings.where("start_date >= '#{Date.today}'")
    @future_bookings.sort_by { |booking| booking.start_date }
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.boat = @boat
    @booking.user = current_user
    authorize @booking
    if @booking.end_date && @booking.start_date
      @booking.cost = (@booking.end_date - @booking.start_date).to_f * @booking.boat.price.to_f.abs
    else
      @booking.value = 0
    end
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @boat = @booking.boat
  end

  def edit
    @user = current_user
    new_id = @booking.boat_id
    @boat = Boat.find(new_id)
    @booking.cost = (@booking.end_date - @booking.start_date).to_f * @boat.price.to_f.abs
  end

  def update
    new_id = @booking.boat_id
    @boat = Boat.find(new_id)
    @booking.update(booking_params)
    @booking.cost = (@booking.end_date - @booking.start_date).to_f * @boat.price.to_f.abs
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking.destroy

    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :boat_id, :cost, :start_date, :end_date, :confirmed_booking)
  end

  def find_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def find_boat
    @boat = Boat.find(params[:boat_id])
    authorize @boat
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @boats = Boat.limit(6).order('created_at DESC');
    @bookings = Booking.limit(1).order('created_at DESC');
    @reviews = Review.limit(1)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_booking, only: [:new, :create]

  def index
    @reviews = policy_scope(Review)
  end
  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to boat_path(@booking.boat)
    else
      render :new
    end
  end

  def show
    @review = Review.new
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def find_booking
    @booking = Booking.find(params[:booking_id])
    authorize @booking
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
        <div class="p-5 mt-5 rounded justify-content-center">
         <%= simple_form_for @boat, html: { class: "form-new"} do |f| %>
           <%= f.input :name, :input_html => { :class => 'foo' }%>
           <%= f.input :boat_type, collection: ["Bracera", "Banana-Boat", "Barge", "Dinghy", "Pedalo", "Punt", "Yacht", "Ship", "Catamaran", "Hovercraft"], as: :select %>
           <%= f.input :docked, as: :select %>
           <%= f.input :location %>
           <%= f.input :price, input_html: { min: 0, step: 'any' } %>
           <%= f.input :guests, input_html: { min: 0, max: 100, step: 'any' } %>
           <%= f.input :image_url %>
           <%= f.submit %>
        <% end %>
       <%= link_to 'back', boats_path, class: "button-new" %>
     </div>
    </div>
  </div>
</div>

app/views/boats/index.html.erb
<div class="container">
<div class="search-bar">
<%= form_tag boats_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a boat by name or location"
  %>
</div>
  <div class="search-bar-logo">
  <%= submit_tag "Search", class: "btn btn-primary" %>
  </div>
</div>

<div class="home-card-container">
<div class="home-cards">

<% end %>
  <% @boats.each do |boat| %>
  <div class="home-card-category">
    <%= link_to boat_path(boat) do %>
    <%= image_tag("#{boat.image_url}", class:"boat-img-card img-thumbnail")%>
      <div class="card-body">
      <h4 class="boat-card-text"><%= boat.name %>
      <h5 class="home-card-text-small"><i class="fa-solid fa-sterling-sign"></i>&nbsp;<%= boat.price %>p/n<br>
      <i class="fa-solid fa-bed"></i>&nbsp;<%= boat.guests %>
      &nbsp;&nbsp;<i class="fa-solid fa-location-arrow"></i>&nbsp;<%= boat.location %>
      </h5>
        </div>
    <% end %> <!-- end of link_to -->
    </div>
    <% end %> <!-- end of boat.each -->
</div>
</div>

app/views/boats/new.html.erb
 <div class="banner-new">
   <div class="container">
     <div class="new_header">
       <h1 class="ml15">
         <span class="word">Host</span>
         <span class="word">your</span>
         <span class="word">own</span>
         <span class="word">boat</span>
       </h1>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
       <%= render 'form' %>
    </div>
   </div>

</div>

app/views/boats/show.html.erb
<div class="container-hero">

  <div class="container-info shadow bg-white rounded m-3 p-3">
  <div class="boat-title">
    <h1><%= @boat.name %></h1>
  </div>
      <div class="boat-info">
        <p> Docked? - <% if @boat.docked %>
          <%= "Yes" %>
        <% else %>
          <%= "No" %>
        <% end %></p>
        <p> Cost: £<%= @boat.price %> per night </p>
        <p> Boat location <%= @boat.location %> </p>
        <p> Boat Type: <%= @boat.boat_type %> </p>
        <p> Guests: <%= @boat.guests %> </p>
      </div>
  </div>

  <div class="container-img-btn">
    <img class="boat-image" src="<%=@boat.image_url%>">

    </div>
</div>
<div class="container-button">
  <%= link_to 'Back', boats_path, class: "btn btn-lg btn-primary" %>
  <%= link_to 'View Bookings', bookings_path, class: "btn btn-lg btn-primary " %>
  <!-- Button trigger modal -->
  <button type="button" class=" btn btn-lg btn-primary" data-bs-toggle="modal" data-bs-target="#new_booking_modal">Book this Boat</button>
  <%= render "bookings/new" %>
</div>

<div>
<div class="container-reviews p-5 m-5 shadow bg-white rounded">
  <h2>Reviews for <%= @boat.name %></h2>
  <% @bookings.each do |booking| %>
    <div>
      <% booking.reviews.each do |review|%>
      <p><%= '⭐️' * review.rating.times do %></p>
      <% end %>
      <p class="mb-0"><%= review.comment %></p>
      <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
    <% end %>
    </div>
  <% end %>
</div>

app/views/bookings/_form.html.erb
<div class="p-5 mt-5 shadow bg-white rounded justify-content-center">
  <%= simple_form_for @booking do |f| %>
    <%= f.input :start_date, html5: true, input_html: {class: "datepicker"}  %>
    <%= f.input :end_date, html5: true, input_html: {class: "datepicker"}  %>
    <%= f.button :submit, "Book Boat", class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/bookings/_new.html.erb
<div class="modal fade" id="new_booking_modal" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Book <%= @boat.name %> Boat</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@boat, @booking], data: { unavailable_dates: @boat.unavailable_dates.to_json } do |f| %>
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book Boat", class: 'btn btn-primary', method: :create, data:{ confirm: "Confirm Booking?"}%>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2><%= @boat.name %></h2>

    <%= simple_form_for [@boat, @booking], data: { unavailable_dates: @boat.unavailable_dates.to_json }, html:{id: :edit_booking} do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book Boat", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<h1 class="text-center p-2">Future Bookings</h1>

<div class="home-card-container">
<div class="booking-home-cards">
  <% @future_bookings.each do |booking| %>
  <div class="home-card-category">
    <%= link_to booking_path(booking) do %>
    <%= image_tag("#{booking.boat.image_url}", class:"boat-img-card img-thumbnail")%>
      <div class="card-body">
      <h4 class="boat-card-text"><%= booking.boat.name %>
      <h5 class="home-card-text-small"><i class="fa-solid fa-moon"></i>&nbsp;<%= (booking.end_date - booking.start_date).to_i %> Nights<br>
      <h5 class="home-card-text-small"><i class="fa-solid fa-calendar-days"></i></i>&nbsp;<%=booking.start_date.strftime("%d-%m-%Y") %> - <%= booking.end_date.strftime("%d-%m-%Y") %><br>
      <h5 class="home-card-text-small"><i class="fa-solid fa-sterling-sign"></i>&nbsp;<%= booking.cost%> Total<br>
      <h5 class="home-card-text-small"><i class="fa-solid fa-location-arrow"></i>&nbsp;<%= booking.boat.location%>
      </h5>
        </div>
    <% end %> <!-- end of link_to -->
    </div>
    <% end %> <!-- end of boat.each -->
</div>
</div>

<h1 class="text-center p-2">Past Bookings</h1>

<div class="home-card-container">
<div class="booking-home-cards">
  <% @past_bookings.each do |booking| %>
  <div class="home-card-category">
    <%= link_to booking_path(booking) do %>
    <%= image_tag("#{booking.boat.image_url}", class:"boat-img-card img-thumbnail")%>
      <div class="card-body">
      <h4 class="boat-card-text"><%= booking.boat.name %>
      <h5 class="home-card-text-small"><i class="fa-solid fa-moon"></i>&nbsp;<%= (booking.end_date - booking.start_date).to_i %> Nights<br>
      <h5 class="home-card-text-small"><i class="fa-solid fa-calendar-days"></i></i>&nbsp;<%=booking.start_date.strftime("%d-%m-%Y") %> - <%= booking.end_date.strftime("%d-%m-%Y") %><br>
      <h5 class="home-card-text-small"><i class="fa-solid fa-sterling-sign"></i>&nbsp;<%= booking.cost%> Total<br>
      <h5 class="home-card-text-small"><i class="fa-solid fa-location-arrow"></i>&nbsp;<%= booking.boat.location%>
      </h5>
        </div>
    <% end %> <!-- end of link_to -->
    </div>
    <% end %> <!-- end of boat.each -->
</div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2><%= @boat.name %></h2>

    <%= simple_form_for @booking, data: { unavailable_dates: @boat.unavailable_dates.to_json } do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book Boat", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container-hero">
  <div class="container-info shadow bg-white rounded m-3 p-3">
    <h1><%= @booking.boat.name %></h1>
        <p>Total trip cost: <strong>£<%= @booking.cost %></strong></p>
        <p>You have booked from <strong><%= @booking.start_date.strftime("%d-%m-%Y") %> to <%= @booking.end_date.strftime("%d-%m-%Y") %></strong></p>
        <p>Your total trip will be: <strong><%= (@booking.end_date - @booking.start_date).to_i %> days</strong></p>
        <p>Boat-location: <strong><%= @booking.boat.location %> </strong></p>
        <p>Pack your swim gear and get ready to rumble!</p>
      </div>

  <div class="container-img-btn">
    <img class="boat-image" src="<%=@booking.boat.image_url%>">
  </div>
</div>
<div class="container-booking-btn">
  <%= link_to 'Cancel Booking', booking_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"%>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#new_booking_modal">Update Booking</button>
  <%= link_to 'Add a Review', new_booking_review_path(@booking), class: "btn btn-primary" %>
  <%= render "bookings/new" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boatee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/alerts' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="">
  <div class="container">
    <h1>BOATEE</h1>
    <p class="ml14">
      <span class="text-wrapper">
        <span class="letters">Discover an Ocean of Travel</span>
        <span class="line"></span>
      </span>
    </p>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <%= link_to  'Start Cruising', boats_path, class: "button-home" %>
  </div>
</div>

<%# carousel %>
<h2 class="favourites">Our Top Picks 🛟</h2>
<div class="container">
  <div class="row justify-content-center">
    <div id="carouselExampleControls" class="carousel slide carousel-dark" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% @boats.each_with_index do |boat, i| %>
          <div class="carousel-item <%= i == 0 ? "active" : "" %>">
            <div class="card-wrapper">
              <div class="home-card-category">
                <%= link_to boat_path(boat) do %>
                  <%= image_tag("#{boat.image_url}", class:"card-img-top img-thumbnail")%>
                  <div class="card-body">
                    <h4 class="home-card-text"><%= boat.name %>
                      <% @reviews.each do |review| %>
                        <%= '⭐️' * review.rating %>
                      <% end %>
                    </h4>
                    <h5 class="home-card-text-small"><i class="fa-solid fa-sterling-sign"></i>&nbsp;<%= boat.price %>p/n<br>
                      <i class="fa-solid fa-bed"></i>&nbsp;<%= boat.guests %>
                    </h5>
                  </div>
                <% end %> <!-- end of link_to -->
              </div>
            </div>
          </div>
        <% end %>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<div class="container">
<h1 class="align-text-center">Add a review</h1>
  <div class="p-5 mt-5 shadow bg-white rounded justify-content-center">
    <%= simple_form_for [@booking, @review] do |f| %>
      <%= f.input :comment, html5: true %>
      <%= f.input :rating, html5: true %>
      <%= f.button :submit, "Submit Review", class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<%= render "form" %>

app/views/reviews/show.html.erb
<h1>Reviews</h1>

<%= @review.comment %>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> Travel
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("Boatee.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

     <div class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link" %>
      <%= link_to "Host your boat", new_boat_path(@boat), class: "nav-link" %>
      <%= link_to "View Boats", boats_path, class: "nav-link" %>
       <%= link_to "Bookings", bookings_path, class: "nav-link last-link" %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.8RpiPi1ZlOup705tqVC2LAHaHa%26pid%3DApi&f=1", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>